// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCG-iaVI2AYMM5a0HUQBnvzJBD-l0CjgVE',
    appId: '1:623865730635:web:5066f0deca6767069b1fce',
    messagingSenderId: '623865730635',
    projectId: 'tathkarah-122bc',
    authDomain: 'tathkarah-122bc.firebaseapp.com',
    storageBucket: 'tathkarah-122bc.appspot.com',
    measurementId: 'G-KT377MT12Q',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEWgavLfugTA1KWaJJ5AgvVLKVl-JubFg',
    appId: '1:623865730635:ios:513626c3f74ae6f99b1fce',
    messagingSenderId: '623865730635',
    projectId: 'tathkarah-122bc',
    storageBucket: 'tathkarah-122bc.appspot.com',
    iosClientId: '623865730635-snr8a4mbmh691qovjpljo33jq3e6mu4d.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEWgavLfugTA1KWaJJ5AgvVLKVl-JubFg',
    appId: '1:623865730635:ios:513626c3f74ae6f99b1fce',
    messagingSenderId: '623865730635',
    projectId: 'tathkarah-122bc',
    storageBucket: 'tathkarah-122bc.appspot.com',
    iosClientId: '623865730635-snr8a4mbmh691qovjpljo33jq3e6mu4d.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCG-iaVI2AYMM5a0HUQBnvzJBD-l0CjgVE',
    appId: '1:623865730635:web:c6395d964f0fa24d9b1fce',
    messagingSenderId: '623865730635',
    projectId: 'tathkarah-122bc',
    authDomain: 'tathkarah-122bc.firebaseapp.com',
    storageBucket: 'tathkarah-122bc.appspot.com',
    measurementId: 'G-K3BPDP6CMC',
  );

}